name: transfer_chess
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - setuptools
  - pytorch=1.4.0
  - torchvision=0.5.0
  - cudatoolkit=10.1
  - cudnn=7.6.5
  - tensorflow-gpu=2.1.0
  - numpy=1.18
  - pandas
  - scikit-learn=0.22
  - scipy=1.4
  - jupyter
  - notebook
  - matplotlib
  - seaborn
  - h5py
  - pyyaml
  - tqdm
  - pip
  - pip:
    - python-chess==0.30.1
    - tensorboardx==2.0
    - humanize==2.4.0
    - natsort==7.0.1