name: Chesster CI

on: [push, pull_request]

defaults:
  run:
    # This ensures that all systems use the same syntax for
    # shell commands when running the workflow.
    shell: bash

permissions:
  contents: read

jobs:
  test-python:
    name: Python Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ["3.10"]

    steps:
    - name: Checkout repo
      id: python-checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      id: python-setup
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      id: python-dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run unit tests on Python files with coverage
      id: python-tests
      run: |
        coverage run -m pytest
    
    - name: Create code coverage report
      id: python-coverage-report
      run: |
        coverage report --fail-under=80
    
    - name: Lint Python files with pylint
      id: python-lint
      # ensure that the linter will run even if previous steps fail
      if: always()
      run: |
        pylint --rcfile=pylintrc $(find . -type f -name "*.py")

  test-typescript:
    name: TypeScript Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout repo
        id: ts-checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: nodejs-setup
        uses: actions/setup-node@v6

      - name: Install Dependencies
        id: ts-dependencies
        run: npm ci
        
      - name: Test
        id: ts-test
        run: npm run test

      - name: Lint TypeScript files with gts
        id: ts-lint
        # Ensure the linter will always run, even if previous steps fail.
        if: always()
        run: npm run lint
